Update patch set 6
Patch Set 6: Code-Review-2

Doesn't seems to work Still have some errors (swig-4.0.1-3.fc31.x86_64)

In AccountService.java, line 709
error: cannot find symbol method set(String,String)

line 739:
error: no suitable constructor found for UintVect(int)
constructor UintVect.UintVect(long[]) is not applicable
(argument mismatch; int cannot be converted to long[])
constructor UintVect.UintVect(Iterable<Long>) is not applicable
(argument mismatch; int cannot be converted to Iterable<Long>)
constructor UintVect.UintVect(UintVect) is not applicable
(argument mismatch; int cannot be converted to UintVect)

1476:
error: cannot find symbol method set(String,enabled ? [...]alse")

Daemon service, line 149
error: cannot find symbol method empty()

247
error: cannot find symbol method empty()


ProfileChunk 41
error: no suitable constructor found for StringVect(long)
constructor StringVect.StringVect(String[]) is not applicable
(argument mismatch; long cannot be converted to String[])
constructor StringVect.StringVect(Iterable<String>) is not applicable
(argument mismatch; long cannot be converted to Iterable<String>)
constructor StringVect.StringVect(StringVect) is not applicable
(argument mismatch; long cannot be converted to StringVect)

Patch-set: 6
Reviewer: Gerrit User 220 <220@1e26b4c1-6b8c-47ff-9df7-501b633d3b5a>
Label: Code-Review=-2