Update patch set 11
Patch Set 11:

Still a problem at the end with nettle (this one from system). Will check later

/usr/bin/ld: /home/amarok/Projects/jami/daemon/contrib/x86_64-redhat-linux/lib/libopendht.a(libopendht_la-crypto.o): undefined reference to symbol 'nettle_gcm_aes_decrypt@@NETTLE_7'
/usr/bin/ld: /usr/lib64/libnettle.so.7: error adding symbols: DSO missing from command line

Patch-set: 11
Reviewer: Gerrit User 220 <220@1e26b4c1-6b8c-47ff-9df7-501b633d3b5a>
Label: Code-Review=0