dbus: Ajdust object names to conform to D-Bus spec.
This started failing recently, probably due to tooling becoming more
strict about the D-Bus specification, with errors like:

  bin/dbus/cx.ring.Ring.PluginManagerInterface.xml:1:40:
   error: Invalid D-Bus object path '/cx.ring.Ring.Instance' found
   while parsing introspection

The names were adjusted using the following command:

  find bin/dbus -name '*.xml*' |
  xargs sed -i 's,/cx.ring.Ring.,/cx/ring/Ring/,'

Change-Id: I7c72d47e01535be524aeab27b2f1e542142f3bdc