disable vdpau in ffmpeg
Fixes an issue where Ring would sometimes fail to build because
of an undefined reference to "vdp_device_create_x11".

VDPAU should be re-enabled once it is implemented.

Change-Id: Idc420931674f7455a6ae561afa9da6e5808d78fb